apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCNKwiV8PQtB6dxNjNFVXTHIaVNGjnTiXSW+nJPMhCKiUnA48OryzFppfztFreHRB3OU0iwG3Cjs1nSIogV0KpqzrtHFoSYDykFk/vThh1lPmT8GuSRYPALIoWL1XEoGSf76XeklwygVfbspoGOlPVZIX3LMjkGXC/5cddNdtLkZT2Kwii3qje8f4+Y1ucj9oOgqgqvXbX0Xtf7cDnJf8KTQfvw5Gn7SoumrT8ar2FmJYwFcPldyyZdDNyYJJpBcEqXF6ZDZuOqKfOMScsVPLWrynreXfQypEERcCMjyAdFONKv8RE5Vn0+Gg0EWX6ga6PF55sEPAHudDZ+cwYtOTCZweZqevNHxqQSuvxqyjpK1dsiGwTHyfXbaoeP8sQ6AOxllN5HocAiiPDmBOGaTNAY/RIQ0B+QL/OX1cR6lAT2KK8nMLdrvxGc5rLql0oxhJvnIbAhUqk4aJo7PlkGcLHiQfn5n2iUmaj6itlQkDs8T1aVM7vL3mAt5AYHQKCi7K09Yf/nmjyo89P5YIAT18q9ge+D1sCHAbJSxrBm5R08wAoCqY5bV9gvxH66KMyOj0eJKMuqmzGBf5fhpYZuT2i7+KIvTna717ohxwn4TJizEn+uwASWttB9u4tt9/NnP4AMHXyFsE4YmZ5c3qgXMuXb00qV10gws959f9zB9jxgrB5FvtmWRRysDAMYgSf3RIp/y/VFfeTXOu5NOuWqblhlhnginw==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
