apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgC9Of4TofM+G8TXkdM12QisQ4N/XsklQKPJs3JXdYSYfBu2grvs2mGEHAEyBXuevSlFkV3Vh3Nr+Zev/XUtBGeV/JyuxrWV95ZSowHPvJirkPHD9fE/kHcLV6MjeY8E2pK6TfuovckML9/St4ueV+X0vwvzUrT80gNXq/Li8420FExE779bjm8XZzfbh6Ffk33xhgrD0wGjh8bhLkiGUbpbUTp4WXuITry3MdaXhlT918dO2Ej2gTuGNRJdzd1Rsv4ebrUCGF8rV+/xGg/CPoYURsuPHUXyBaFDJxFasFosyrNZBPOT48AhPZYOF50hf4vMohzRwhDk6SHAzouS0iHzX81jFJosKZvKFfAsXmsVkERCpHgFZpgVnqGtzfLo5JWcVm2aXsAZOAvJHEKnOA62XLoikmqFIfdJSXiIrqeGOEFoNfqRSSy824a5t75AqgPYydcUUqAVblJzw9uiaR+eLKSsEyU/2UcbTZTUYN0D2vMuU8EmnxQDHytT6qjFCgP+s2vJ0B6eQvu1VFnd6IlEmS7TSr31KCtmQ3/T4m74v4WSghXCmzWZfOyBdTyvDpDcnyyDBrOiUvXte1A6JYY+63KGDbC0oyz9IWL0KS6Nu3qU9QsZPaTmJ57LZ6kGGH+C/OOzK5Jdai3DaX7K+Al4a4O7m9qIztDxDZxj8/vzZBxeA8jvQAlasKcqvfb3/pWvKK24opNVOx/78hO28CbFes2WkQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
